Repository Unidata/netcdf-c, pull requests merged in 2019-11, with the labels that each got.

#1508 Added EXTERNL definition in netcdf_par.h
  include/nc4internal.h
  include/nc_tests.h
  libdap2/dapdump.c
Labels: area/parallel

#1514 Changes to make it possible to nest this project inside of another CMake project.
  CMakeLists.txt
  libsrc/CMakeLists.txt
  ncdap_test/CMakeLists.txt
Labels: area/build/cmake

#1526 cleaned up test handling of strings
  nc_test4/tst_interops6.c
Labels: area/tests
