Repository Unidata/netcdf-c, pull requests merged in 2022-03, with the labels that each got.

#2039 Various fixes
  libdispatch/dauth.c
  libdispatch/drc.c
  libdispatch/ncuri.c
  libsrc/ncx.m4
  libsrc/v1hpg.c
  libsrc/var.c
Labels: status/under review, priority/high

#2050 Fix Compiler Strict Aliasing Rule Violations
  libdap4/d4dump.c
  libdap4/d4util.h
  libdispatch/daux.c
  libsrc/ncx.m4
  oc2/xxdr.c
Labels: status/under review, priority/high

#2089 Don't assert if trying to open truncated file from memory.
  libhdf5/hdf5file.c
  libhdf5/nc4memcb.c
  nc_test4/CMakeLists.txt
  nc_test4/tst_broken_files.c
Labels: priority/high

#2246 Rebase of #2103
  CMakeLists.txt
Labels: rebase

#2247 Rebase of #2104
  ncdump/ncdump.c
Labels: arch/any, rebase

#2104 Use canonical path to derive name of dataset on Windows
  ncdump/ncdump.c
Labels: priority/medium
