Repository Unidata/netcdf-c, pull requests merged in 2022-04, with the labels that each got.

#2232 Add BitRound quantization
  include/netcdf.h
  libdispatch/dvar.c
  libhdf5/hdf5open.c
  libhdf5/hdf5var.c
  libhdf5/nc4hdf.c
  libnczarr/zsync.c
  libnczarr/zvar.c
  libsrc4/nc4var.c
  nc_test4/tst_quantize.c
  ncgen/genbin.c
  ncgen/genc.c
  ncgen/ncgen.h
  ncgen/ncgen.l
  ncgen/ncgen.y
  ncgen/ncgenl.c
  ncgen/ncgeny.c
  ncgen/ncgeny.h
Labels: priority/high

#2277 Conflict resolution
  .github/workflows/run_tests_osx.yml
  CMakeLists.txt
  RELEASE_NOTES.md
  config.h.cmake.in
  configure.ac
  dap4_test/test_common.h
  include/nc_tests.h
  include/ncrc.h
  libdap4/d4file.c
  libdap4/d4includes.h
  libdap4/d4util.c
  libdap4/ncd4.h
  libdispatch/dcrc32.c
  libdispatch/dinfermodel.c
  libdispatch/dinstance.c
  libdispatch/dpathmgr.c
  libdispatch/dutil.c
  libsrc/XGetopt.c
  libsrc/ncFile.c
  libsrc/ncio.c
  nc_perf/tst_compress.c
  nc_perf/tst_compress_par.c
  nc_perf/tst_files2.c
  nc_perf/tst_files3.c
  nc_perf/tst_mem.c
  nc_test/tst_diskless5.c
  nc_test/tst_diskless6.c
  nc_test/tst_inmemory.c
  nc_test/tst_misc.c
  nc_test4/tst_camrun.c
  nc_test4/tst_udf.c
  ncdap_test/t_auth.c
  ncdump/CMakeLists.txt
  ncdump/Makefile.am
  ncdump/acpget.c
  ncdump/nctrunc.c
  ncdump/ocprint.c
  ncdump/run_cygutf8.sh
  ncdump/test_unicode_path.sh
  ncdump/tst_cygutf8.c
  ncgen3/run_nc4_tests.sh
  nczarr_test/ref_zarr_test_data.cdl.gz
  nczarr_test/run_interop.sh
  test_common.in
Labels: Conflict Resolved

#2297 Remove on-push trigger for OSX-based workflows.
  .github/workflows/run_tests_osx.yml
  .github/workflows/run_tests_ubuntu.yml
Labels: area/tests, priority/immediate
